spring:
  profiles:
    active: druid

  main:
    allow-bean-definition-overriding: true

  # 如果你是微服务的话，它起到了唯一标识的作用，（不然你怎么让注册中心知道你注册的这个服务实例，逻辑上是属于哪个服务的）
  # 像nacos的话，你要是使用它当做配置中心，去拉取配置文件的时候，默认配置下它会当成参数组装成key，去请求配置文件
  # 单体应用的话，一般用不上
  application:
    name: springboot-study

  # redis
  redis:
    password: 123456
    database: 0
    lettuce:
      pool:
        max-active: 10
        max-idle: 20
        min-idle: 10
        max-wait: -1
    host: 127.0.0.1
    port: 6379
    timeout: 30000


server:
  port: 9090
  servlet:
    context-path: /springboot-study

# Swagger 3
# 生产环境需设置为false
springfox:
  documentation:
    swagger-ui:
      enabled: true

# mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以不配置  实体类字段上加上@TableLogic注解)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
