server:
  port: 9090
  servlet:
    context-path: /springboot-study

spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: master,slave2,slave1
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3310/study?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/study?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      slave2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3308/study?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
    props:
      sql.show: true
    masterslave:
      load-balance-algorithm-type: round_robin
    sharding:
      master-slave-rules:
        master:
          master-data-source-name: master
          slave-data-source-names: slave1,slave2

#  sharding:
#    jdbc:
#      datasource:
#        master1:
#          type: com.zaxxer.hikari.HikariDataSource
#          jdbc-url: jdbc:mysql://localhost:3310/study?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
#          hikari:
#            driver-class-name: com.mysql.cj.jdbc.Driver
#          password: 12root
#          username: test
#        names: master1,slave0
#        slave0:
#          hikari:
#            driver-class-name: com.mysql.cj.jdbc.Driver
#          password: 12root
#          username: test
#          jdbc-url: jdbc:mysql://localhost:3310/study?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
#          type: com.zaxxer.hikari.HikariDataSource
#      config:
#        masterslave:
#          load-balance-algorithm-type: round_robin
#          name: ms
#          master-data-source-name: master1
#          slave-data-source-names: slave0
#        props:
#          sql:
#            show: 'true'


  redis:
    password: 123456
    database: 0
    lettuce:
      pool:
        max-active: 10
        max-idle: 20
        min-idle: 10
        max-wait: -1
    host: 127.0.0.1
    port: 6379
    timeout: 30000


#  application:
#    name: springboot-test-exam1
#  datasource:
#    # 使用阿里的Druid连接池
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    # 填写你数据库的url、登录名、密码和数据库名
#    url: jdbc:mysql://localhost:3310/study?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
#
#
#    # druid 连接池配置
#    druid:
#      # 连接池的配置信息
#      # 初始化大小，最小，最大
#      initial-size: 5
#      min-idle: 5
#      maxActive: 20
#      # 配置获取连接等待超时的时间
#      maxWait: 60000
#      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      timeBetweenEvictionRunsMillis: 60000
#      # 配置一个连接在池中最小生存的时间，单位是毫秒
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: SELECT 1
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      # 打开PSCache，并且指定每个连接上PSCache的大小
#      poolPreparedStatements: true
#      maxPoolPreparedStatementPerConnectionSize: 20
#      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，stat:监控统计、log4j：日志记录、wall：防御sql注入
#      filters: stat,wall,slf4j
#      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
#      # 配置DruidStatFilter
#      web-stat-filter:
#        enabled: true
#        url-pattern: "/*"
#        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
#      # 配置DruidStatViewServlet
#      stat-view-servlet:
#        url-pattern: "/druid/*"
#        # IP白名单(没有配置或者为空，则允许所有访问)
#        allow: 127.0.0.1,192.168.163.1
#        # IP黑名单 (存在共同时，deny优先于allow)
#        deny: 192.168.1.73
#        #  禁用HTML页面上的“Reset All”功能
#        reset-enable: false
#        # 登录名
#        login-username: admin
#        # 登录密码
#        login-password: 123456

    # Hikari 连接池配置
    # 最小空闲连接数量
#  main:
#    allow-bean-definition-overriding: true
#    hikari:
#      minimum-idle: 5
#      # 空闲连接存活最大时间，默认600000（10分钟）
#      idle-timeout: 180000
#      # 连接池最大连接数，默认是10
#      maximum-pool-size: 10
#      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
#      auto-commit: true
#      # 连接池名称
#      pool-name: MyHikariCP
#      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
#      max-lifetime: 1800000
#      # 数据库连接超时时间,默认30秒，即30000
#      connection-timeout: 30000
#      connection-test-query: SELECT 1


# 生产环境需设置为false
#springfox:
#  documentation:
#    swagger-ui:
#      enabled: true



